### ISSUE TITLE
issues around AppMesh CRD APIs

### ISSUE THREAD

**Issue by M00nF1sh** [aws/aws-app-mesh-controller-for-k8s#146]
## Summarize issues around AppMesh CRD APIs:
By work around with appMesh objects a lot recently, I feel the below semantic issues around AppMesh CRD APIs

## Core problems:
1. VirtualService's namespace scope is not respected by the controller
    Under different namespace, two k8s VirtualService object can coexists and representing a single AppMesh VirtualService object. While the VirtualService CRD itself is namespace scoped,  the namespace is only utilized to resolve name for routes/targets it references to. E.g. If user have two VirtualService with same name in different k8s namespace, and reference same mesh. The controller will treat them as same AppMesh VirtualService object, thus will endlessly reconcile them back and forth.

2. VirtualNode CRD have ambiguous naming hacks. 
     Under same namespace, two k8s VirtualNode object can coexists and representing a single AppMesh VirtualNode object. e.g. `node-name` and `node-name.namespace` is same AppMesh object while different k8s object. However, k8s object semantically can have "." inside name, and if customer do that, it will be treated as namespace separator by us.
e.g. valid k8s objects like <namespace-a: node-name>, <namespace-a: node-name.namespace-a>, <namespace-b: node-name.namespace-a> is actually reference the same AppMesh VirtualNode.

3. The reference between VirtualService & VirtualNode is ambiguous.
    an VirtualService can reference virtualNode via either `node-name` or `node-name.namespace`. and will automatically backfill namespaces since there isn't a "." inside. This is ambiguous since "." can appear in a valid k8s object name.

4. Based on above conditions, All objects in appMesh is always namespace scoped by Kubernete's namespace.  However, it don't have to be in such case. e.g. ideally, I may want a service called "auth" instead of "auth.namespace" inside appMesh. Also, since AppMesh is meant to be able to span multiple clusters/platforms, it's important to allow user freely determine the name in AppMesh, since simple namespace scope don't work under such case.

5. The default logic to determine the set of pods that belongs to an VirtualNode is tricky. 
   It relies on <deployment-namespace: deployment-name> to be same as <virtualnode-namespace: virtual-nodename>. Which is ambiguous since it relies on the fact the pods are managed by *Replicaset* and then by *Deployment* objects,  and this condition is not always true.     
   Also, a minor issue is that the logic allows pod to use annotation to specify the virtualNode directly. I think it's kind of "Inversion of Control". since it should be VirtualNode's ability to "select" set of pod that should belong to it, instead of "pod" select virtualNode.

## Minor problems:
1. The AppMesh virtual node name is calculated as `<node-name>-<node-namespace>`. while "-"  can appear in valid object name for k8s objects. "_" will be a better choice.
2. The Injector relies on a global mesh name to be set. While there can be multiple mesh in side a single cluster.
3. The virtualService always requires a virtualRouter.Which is not the case in appMesh API, where a virtualNode can be backend for virtualService without router. Also, this forbids us to reuse a single virtualRouter for different virtualServices. ideally, i can have virtual service "svc" and "svc.namespace" using same virtualRouter.

### Minor changes:
1. virtualService should reference virtualNode things like below(if we don't go the `Aggressive ideas` approach below)
```
virtualNodeRef:
     namespace: ns-a,
     name: vn-name
``` 

### Aggressive ideas:
1. Kubernetes namespaces seems to be a nature fit to represent a AppMesh mesh. E.g. users ca n annotate an kubernetes namespace with an annotation of "appMesh" mesh name, then any appMesh CRD created inside that namespace is belongs to this mesh.
    * we can have k8s VirtualService Objects like "my-svc", "my-svc.ns", "my-svc-ns.cluster.local" inside a single namespace, and create corresponding different AppMesh object.
    * If we decouple the namespace for AppMesh objects from the application namespaces, then it's more clear. 
    * we should treat appmesh objects's namespace different than application namespaces since ideally an Appmesh object can target objects in different kubernetes namespace. e.g. an "company-api' VirtualService should route to pods in "team-a" namespace  for `/auth` APIs, and route to pods in "team-b" namespace for `/product` APIs
2. VirtualNode explicitly select set Pods via namespace & selector.

**Comment by stefanprodan** [comment]
Relates to #15

**Comment by nckturner** [comment]
Agreed that the minor change makes sense if we don't do anything else.  The magic append of namespace is a headache.

> VirtualService's namespace scope is not respected by the controller
Under different namespace, two k8s VirtualService object can coexists and representing a single AppMesh VirtualService object. While the VirtualService CRD itself is namespace scoped, the namespace is only utilized to resolve name for routes/targets it references to. E.g. If user have two VirtualService with same name in different k8s namespace, and reference same mesh. The controller will treat them as same AppMesh VirtualService object, thus will endlessly reconcile them back and forth.

This is certainly an issue.  The virtual service names are not automatically namespaced which potentially leads to multiple custom resources using the same virtual service in App Mesh when virtual service custom resources are created with the same name in different namespaces.  

> we can have k8s VirtualService Objects like "my-svc", "my-svc.ns", "my-svc-ns.cluster.local" inside a single namespace, and create corresponding different AppMesh object.

Do you mean tell the controller which namespace to look for custom resouces in?

> If we decouple the namespace for AppMesh objects from the application namespaces, then it's more clear.

Again, are you saying here to put all App Mesh custom resouces into a single namespace?  Or allow them to be in any namespace? 

> 2. VirtualNode explicitly select set Pods via namespace & selector.

I actually really wanted to do this in the initial design, but there were some issues.  Basically, because the envoy needs to know the virtual node name at startup and individual pods can be labeled at runtime, a running pod would not be able to dynamically change its virtual node by adding a label, which I thought was a slightly bad experience by breaking some Kubernetes UX assumptions, because you can dynamically add a pod to a service by adding a label.

**Comment by nckturner** [comment]
Once we agree on the issues we can spin them off into separate tracking issues divided into bugs and enhancements.

**Comment by stefanprodan** [comment]
> we can have k8s VirtualService Objects like "my-svc", "my-svc.ns", "my-svc-ns.cluster.local" inside a single namespace, and create corresponding different AppMesh object.

I don't think this the right thing to do, it would break RBAC. Also you will not be able to bundle VS/VNs with your app definitions in a helm chart since charts are limited to a single namespace.

**Comment by M00nF1sh** [comment]
will reopen once clarified stuffs with team first :D
