### ISSUE TITLE
CloudConfig BindFlags is binding region for accountID which is not correct.

### ISSUE THREAD

**Issue by jane829** [aws/aws-app-mesh-controller-for-k8s#329]
When I am trying to install appmesh controller to aws eks cluster based on Fargate,  we got an error:  "unable to initialize AWS cloud", even we specify the aws-account-id, it's still not working, as we find the source code is point the region's value to the accountId, which means we can never set accountId correctly. 

![image](https://user-images.githubusercontent.com/6086222/89311881-26621280-d6a9-11ea-809a-c6e87115eff6.png)

if this can be fixed as soon as possible? thanks in advance.

**Comment by fawadkhaliq** [comment]
@jane829 thanks for filing the issue. We'll fix this in the 1.1.1 release

**Comment by fawadkhaliq** [comment]
#330 fixes the issue. It'll be released in next release (1.1.1)

**Comment by jane829** [comment]
ok, thanks. May I ask when can we expect to have release 1.1.1 been published?
Besides, I had another question, we are trying to integrate AppMesh with EKS fargate, but the cluster need to be private and in a private only vpc for security requirement. However,  currently the Appmesh controller is default to use Global sts service for a series of request, which is not working for us. I am wondering if this can be fixed asap and when can we expect it to be fixed and published? Or is there any workaround?  cheers

**Comment by fawadkhaliq** [comment]
@jane829 you can track 1.1.1 progress in this milestone https://github.com/aws/aws-app-mesh-controller-for-k8s/milestone/6  

Here's a similar issue filed (https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/328) where STS endpoint override is needed for the same use-case. Since there is no workaround, we will try to get this in 1.1.1 as well. Please keep an eye on issue https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/328 for update on the fix and release
