### ISSUE TITLE
Allow override for default Envoy sidecar

### ISSUE THREAD

**Issue by rafaelpereyra** [aws/aws-app-mesh-controller-for-k8s#350]
Virtual Gateway injector uses a [method](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/b4601ea3021b4a0f6c55dde5f70bb21ec103ed44/pkg/inject/utils.go#L75) to identify if the envoy sidecar is already deployed or not based on the name of the pod specified [here](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/fa911c740ffcf835a44a4ef71346b152308ffc41/pkg/inject/envoy.go#L14)

If Virtual Gateway standalone envoy proxy is deployed with a different name in a namespace annotated to inject the sidecar, the mutator will inject a second Envoy proxy into the gateway instead of ignoring the pod [here](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/b4601ea3021b4a0f6c55dde5f70bb21ec103ed44/pkg/inject/virtualgateway_envoy.go#L62).

Maybe a method can be provided to override / specify the name of the Envoy container, at least for the Virtual Gateway. Otherwise provide an annotation to skip the injector in a particular deployment.

It should however be documented at least as a requirement.

**Comment by fawadkhaliq** [comment]
@rafaelpereyra there is annotation [1] to override the virtual gateway Envoy [2]

You can add the annotation `appmesh.k8s.aws/virtualGatewaySkipImageOverride` to skip the override.

+1, the documentation around this is lacking. We'll update the documentation with this

[1] https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/b4601ea3021b4a0f6c55dde5f70bb21ec103ed44/pkg/inject/constants.go#L41
[2] https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/b4601ea3021b4a0f6c55dde5f70bb21ec103ed44/pkg/inject/virtualgateway_envoy.go#L148

**Comment by anand-rajagopal-hub** [comment]
@rafaelpereyra The issue is slightly different. If the name of the container is not "envoy", the app mesh controller is not automatically injecting APPMESH_VIRTUAL_NODE_NAME environment variable causing the gateway pods to crash. Documentation around this would help. If I create my own helm chart to deploy the gateway pods, I thought I could use the name that helm automatically generates using convention. Turns out the code is specifically looking for container name "envoy". https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/b4601ea3021b4a0f6c55dde5f70bb21ec103ed44/pkg/inject/virtualgateway_envoy.go#L62

**Comment by fawadkhaliq** [comment]
@anand-rajagopal-hub thanks for the additional feedback. We will cover this in the documentation as well

**Comment by fawadkhaliq** [comment]
Doc added here: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/364. Here's the doc [link](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/docs/reference/injector.md) outside of PR

This will be synced to out [Live Docs](https://aws.github.io/aws-app-mesh-controller-for-k8s/)
