### ISSUE TITLE
Sidecar Inject/Replacement fails when x-ray tracing is enabled

### ISSUE THREAD

**Issue by marceloboeira** [aws/aws-app-mesh-controller-for-k8s#395]
**Describe the bug**

When trying to use https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/howto-k8s-connection-pools/v1beta2/manifest.yaml.template#L274 with `tracing.enabled=true` && `tracing.provider=x-ray` the pod fails.

**Steps to reproduce**

1. Follow https://github.com/aws/aws-app-mesh-examples/blob/master/walkthroughs/howto-k8s-connection-pools/
1. Enable x-ray tracing for appmeh-controller
1. Restart deployments to pick-up changes
1. See that any deployment with `controller-override` will fail to replace pods and error with a missing `containerPort` definition.

**Expected outcome**

Just work as before...

**Environment**

* App Mesh controller version: 1.2
* Envoy version
* Are you using any integrations? X-ray, Jaeger etc. If so versions? Yes, latest x-ray
* Kubernetes version: 1.18
* Using EKS (yes/no), if so version? 4

**Additional Context**:

**Comment by fawadkhaliq** [comment]
@marceloboeira thanks for reporting the issue.

The issue was introduced here: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/365. xray daemon port is not configured when injecting xray for virtual gateway pods: https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/inject/inject.go#L169

*Impact*
This impact virtual gateway pod specs marked for xRay sidecar injection. There's no impact on virtual nodes

*Workaround*
Specify the xRay sidecar in the virtual gateway pod spec and not rely on the mutator. You could do this by adding the following container to the virtual gateway pod spec. xRay injector does not override the existing xRay container for users who want to bring their our xRay sidecars. 

```
name: xray-daemon
image: amazon/aws-xray-daemon
securityContext:
  runAsUser: 1337
ports:
- containerPort: 2000
  name: xray
  protocol: UDP
env:
- name: AWS_REGION
  value: us-west-2
```

We'll have a fix shortly

**Comment by marceloboeira** [comment]
@fawadkhaliq I was diving into the code yesterday trying to find out where was the issue, and yes, by manually placing the container it worked. Thanks for the fix!

**Comment by fawadkhaliq** [comment]
> One last question is, the `tracing.port` set in the helm chart is ignored when using xray right?

@marceloboeira when using xray, if `tracing.port` is specified, it overrides the default xray daemon port [1]. Since the xray sidecar and envoy are injected together, you can rely on the controller defaults. 

After seeing you question, I checked the helm chart documentation [2] and noticed the comment about `tracing.port` is inaccurate/misleading in the README. We will fix that

[1] https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/inject/config.go#L141
[2] https://github.com/aws/eks-charts/tree/master/stable/appmesh-controller#configuration

**Comment by marceloboeira** [comment]
@fawadkhaliq that's what I thought too following the code but I wasn't sure since the chart documentation mentions something else...

Thanks!
