### ISSUE TITLE
Add description, fields to "explain"

### ISSUE THREAD

**Issue by buzzsurfr** [aws/aws-app-mesh-controller-for-k8s#446]
Credit to @saleem-mirza for the find.

**Is your feature request related to a problem?**
When using `kubectl explain`, the App Mesh resources do not provide additional details about the resource or sub-objects on the resource.

```
$ kubectl explain mesh
KIND:     Mesh
VERSION:  appmesh.k8s.aws/v1beta2

DESCRIPTION:
     <empty>
```

**Describe the solution you'd like**
I want to be able to call (for example) `kubectl explain mesh` and get the description and fields for the mesh. Additionally, I want to traverse those fields and get additional information on sub-objects. For example, calling `kubectl explain mesh.spec` to get the spec field details.

This type of feature would help kubernetes users who are unfamiliar with App Mesh to learn the resources, constructs, and syntax for creating App Mesh resources within kubernetes.

**Describe alternatives you've considered**
None

**Additional research/notes**
I compared the [App Mesh CRD](https://github.com/aws/eks-charts/blob/master/stable/appmesh-controller/crds/crds.yaml) with the [Step Functions CRD for ACK](https://github.com/aws-controllers-k8s/sfn-controller/blob/main/config/crd/bases/sfn.services.k8s.aws_statemachines.yaml) and noticed that the SFN CRD has the schema underneath the version, whereas the App Mesh one does not.

**State machine "explanation"**

```
$ kubectl explain statemachine
KIND:     StateMachine
VERSION:  sfn.services.k8s.aws/v1alpha1

DESCRIPTION:
     StateMachine is the Schema for the StateMachines API

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

   spec	<Object>
     StateMachineSpec defines the desired state of StateMachine

   status	<Object>
     StateMachineStatus defines the observed state of StateMachine
```

**State machine spec "explanation"**

```
$ kubectl explain statemachine.spec
KIND:     StateMachine
VERSION:  sfn.services.k8s.aws/v1alpha1

RESOURCE: spec <Object>

DESCRIPTION:
     StateMachineSpec defines the desired state of StateMachine

FIELDS:
   definition	<string> -required-

   loggingConfiguration	<Object>

   name	<string> -required-

   roleARN	<string> -required-

   tags	<[]Object>

   tracingConfiguration	<Object>

   type_	<string>

```

**Comment by Shreya027** [comment]
I can work on this issue.

**Comment by Shreya027** [comment]
I have been working on this issue to add kubectl explain to App Mesh. I was able to achieve this functionality for CRD version v1beta1 by setting the following  in the CRD generation options. :

`CRD_OPTIONS ?= "crd:trivialVersions=true,crdVersions=v1beta1,preserveUnknownFields=false"`

I was also able to achieve this functionality for CRD version v1 by specifying options as shown below: ( I haven't  explicitly specified  preserveUnknownFields=false, since  v1 version has unknown fields  dropped by default)

`CRD_OPTIONS ?= "crd:trivialVersions=true,crdVersions=v1` 

From my research and implementation, it seems like OpenApi schema (used by kubectl explain) is not published in presence of unknown fields, because of which kubectl explain doesn't give a detailed results.  

Since the current repository uses CRD version v1beta1 with `preserveUnknownFields=true` by default, kubectl explain will not work as you would have expected.

Currently I cannot find any solution to achieve this functionality without losing unknown fields in App Mesh,  so I will be closing this issue for now.  For more reference and details related to this, check the open issue [#104419](https://github.com/kubernetes/kubernetes/issues/104419)
