### ISSUE TITLE
Fix jaeger tracing collector endpoint version

### ISSUE THREAD

**Issue by Efrat19** [aws/aws-app-mesh-controller-for-k8s#536]
**Describe the bug**
Jaeger tracing `collector_endpoint_version` is meant to be `HTTP_JSON` as configured [here](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/50a7999c6de99454152359534fe2536924190836/pkg/inject/jaeger.go#L16) but in my envoy settings - the endpoint version appears as `"collector_endpoint_version": "HTTP_PROTO"`.
It causes problems with latest jaeger collectors which expect tracing as `json` and not `protobuf` and reply with 400 error code.

**Expected outcome**
Same as discribed on the code source, you would expect zipkin `collector_endpoint_version` to be `HTTP_JSON` instead of `HTTP_PROTO`

**Environment**

* App Mesh controller version - `v1.4.1`
* Envoy version - `v1.20.0.1-prod` (also reproduces in `v1.19.1.0-prod`)
* Are you using any integrations? X-ray, Jaeger etc. If so versions? - jaeger  + zipkin reciever
* Kubernetes EKS `v1.20.4-eks-6b7464`
![image](https://user-images.githubusercontent.com/41479945/143189783-d7c50932-d4da-4647-a127-95862b599254.png)

**Comment by cgchinmay** [comment]
Will take a look

**Comment by cgchinmay** [comment]
Hi @Efrat19 was able to repro the issue. Did changing to HTTP_JSON in the envoy config file generate traces ?

**Comment by Efrat19** [comment]
Hi, I use Jaeger though open-telemtry, from image `otel/opentelemetry-collector-contrib:0.38.0`

**Comment by suniltheta** [comment]
This is not an issue from App Mesh envoy configuration. We can still continue to use HTTP_PROTO instead of HTTP_JSON. 

Since the version v1.22 of jaegertracing collector a deprecated field `collector.zipkin.http-port` was removed. Our [appmesh-jaeger](https://github.com/aws/eks-charts/tree/master/stable/appmesh-jaeger) eks-charts is tested to work on jaegertracing/all-in-one:v1.19 . But if we want to use the latest jarger collector version we should add `COLLECTOR_ZIPKIN_HOST_PORT` to the jaeger deployment.


#### For EKS/K8s AppMesh users here are the steps to mitigate the issue:


Identify the jaeger deployment
```
$ kubectl get deploy --all-namespaces
NAMESPACE        NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
appmesh-system   appmesh-controller   1/1     1            1           7h57m
appmesh-system   appmesh-jaeger       1/1     1            1           8m56s   <----
kube-system      coredns              2/2     2            2           8h
```


Edit the jaeger deployment
```
$ kubectl edit deploy/appmesh-jaeger -n appmesh-system
```


Introduce this new variable in the deployment spec. 
> spec -> template -> spec -> containers -> `- name: {{ .Chart.Name }}` -> env -> 

```
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: "9411"
```

earlier we used to rely on deprecated env `COLLECTOR_ZIPKIN_HTTP_PORT` ([link](https://github.com/aws/eks-charts/blob/master/stable/appmesh-jaeger/templates/deployment.yaml#L66)) which is removed from https://github.com/jaegertracing/jaeger/releases/tag/v1.22.0 onwards.
context: https://github.com/jaegertracing/jaeger-operator/issues/1441

**Comment by suniltheta** [comment]
I was able to make jaegertracing/all-in-one:v1.29 work by introducing just the variable `COLLECTOR_ZIPKIN_HOST_PORT `. I have not tested this with `otel/opentelemetry-collector-contrib:0.38.0`. Please let us know if the issue with otel collector could also be the same.

**Comment by ar4096** [comment]
@cgchinmay can we specify which release this will be available in and close the issue or do we need to update the helm chart also ?

**Comment by ar4096** [comment]
@Y0Username Can we add a Pending-Release label and assign it to this ticket if we don't close it ?

**Comment by cgchinmay** [comment]
Our helm chart release is pending. Once we do that we can close this issue

**Comment by suniltheta** [comment]
^ helm chart updated https://github.com/aws/eks-charts/releases/tag/v0.0.73 . Closing this issue.
