### ISSUE TITLE
Add support for configuring APPMESH_ENABLE_IPV6 env var in proxyinit container

### ISSUE THREAD

**Issue by andrewmarklloyd** [aws/aws-app-mesh-controller-for-k8s#646]
**Is your feature request related to a problem?**
Our EKS clusters have IPV6 disabled so the proxy init container on our pods fail to run because the `APPMESH_ENABLE_IPV6` env var is [hard coded](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/inject/init_proxy.go#L50-L51) to `1`.

Here is the error message we see in the init container:
```
ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol
Perhaps ip6tables or your kernel needs to be upgraded.
```

**Describe the solution you'd like**
Similar to how [annotations](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/inject/constants.go) on the pod are exposed to configure options on the proxyinit container, I suggest adding an annotation to set `APPMESH_ENABLE_IPV6=0`.

**Describe alternatives you've considered**
We've investigated building our own image setting APPMESH_ENABLE_IPV6=0 in the entrypoint. This works but requires us to manage the image lifecycle instead of relying on updates to the source image.

For example:
```
FROM 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:v6-prod
ENTRYPOINT [ "/bin/sh", "-c", "APPMESH_ENABLE_IPV6=0", "/opt/amazon/bin/sidecar-proxy-route-manager.sh" ]
```

**Comment by andrewmarklloyd** [comment]
I see that #647 was merged which is great! Thank you for allowing me to contribute to the project, it was really cool.
Should I close this issue or is that up to the maintainers? Also what is the deployment process for the controller? Will that change be incorporated in the `v6-prod` tag or will another one be created?

**Comment by bendu** [comment]
Hey @andrewmarklloyd I have closed the issue. Thank you for contributing!

As for controller release, there are a couple of other changes that we are working on that I want to get into the next release since release is a somewhat manual process. The `v6-prod` tag refers to the init container which sets up the iptables so direct container network traffic into Envoy, which is separate from the controller code in this repo. Your controller changes will land in the appmesh-controller docker image under an ECR repo like `840364872350.dkr.ecr.us-west-2.amazonaws.com/amazon/appmesh-controller` The latest version is currently `v1.7.0` for that image, so most likely the next release will be `v1.8.0`

**Comment by andrewmarklloyd** [comment]
Oh that's right @bendu, I got the images mixed up. That's great thanks for the info on rolling that change out!
