### ISSUE TITLE
Setting appmesh.k8s.aws/sidecarEnv: "ENVOY_LOG_LEVEL=debug" does not change the pod env var

### ISSUE THREAD

**Issue by egkelly** [aws/aws-app-mesh-controller-for-k8s#661]
**Describe the bug**
Setting appmesh.k8s.aws/sidecarEnv: "ENVOY_LOG_LEVEL=debug" in my deployment template annotations does not have an impact on the Envoy sidecar environment variables. 

**Steps to reproduce**

Set envoy log level in the deployment template annotations:
```apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 20
  name: example
spec:
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh:my-mesh
        appmesh.k8s.aws/sds: enabled
        appmesh.k8s.aws/sidecarEnv: 'ENVOY_LOG_LEVEL=debug'
        appmesh.k8s.aws/virtualNode: example
    spec:
      containers:
...
```

**Expected outcome**
I expect to see the ENV vars for the Envoy sidecar to reflect my desired log level, but the pod exclusively comes up with the default `ENVOY_LOG_LEVEL=info`. It's worth mentioning, I've also tried to configure other env vars using this annotation like the `APPMESH_ENVOY_INGRESS_PORT` var with no success. 

**Environment**

* App Mesh controller version - v1.7.0
* Envoy version - v1.22.2.1-prod
* Are you using any integrations? X-ray, Jaeger etc. If so versions? - N/A
* Kubernetes version - 1.23
* Using EKS (yes/no), if so version? - Yes, eks.2

**Comment by BennettJames** [comment]
The log level of envoy can only be configured at the controller level, by setting `--set "sidecar.logLevel=debug"` as part of the helm deployment of the controller. 

`appmesh.k8s.aws/sidecarEnv` can be used to set variables that are not otherwise set by the app mesh controller. However, it generally does not override values that are [directly managed by the controller](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/50bde049292957f78e5813fe9f782278fa6de126/pkg/inject/sidecar_builder.go#L56-L174)  like the log level.

-----

As for `APPMESH_ENVOY_INGRESS_PORT` - it is set as part of a separate init container, and isn't intended to be configurable. I don't believe anything would stop you from being able to set it on the envoy container, but it likely wouldn't have the desired results.

**Comment by egkelly** [comment]
Ah that's good to know, thanks! That fixed my issue :)

**Comment by suniltheta** [comment]
Does it makes sense to apply `m.getCustomEnv(pod)` after `buildEnvoySidecar(variables, customEnv)`? Because even if I set `sidecar.logLevel=error` across mesh level I would like to override the log level on individual Envoy deployments with `appmesh.k8s.aws/sidecarEnv` annotation.

 https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/50bde049292957f78e5813fe9f782278fa6de126/pkg/inject/envoy.go#L87-L95
